sudo: false
language: ruby
rvm:
  - 2.4
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk
cache:
- apt
install: echo "skip bundle install"
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- echo "StrictHostKeyChecking no" > ~/.ssh/config
- git config --global user.email "ci@berkshelf.com"
- git config --global user.name "Berkshelf"
script:
- rubocop .
- foodcritic .
- rspec
