sudo: false
language: ruby
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
install: echo "skip bundle install"
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
script:
- cookstyle
- foodcritic .
- rspec
